### ISSUE TITLE
add datasets module

### ISSUE THREAD

**Issue by akeshavan** [nipy/dmriprep#25]
so that its easy for people to download data and get started

**Comment by arokem** [comment]
For inspiration (and for HCP data-grabbing), we can rely on the [pyAFQ data module](https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/data.py). This would entail an (optional?) boto3 dependency, and a dependency on DIPY (which I assume we want anyway).

**Comment by richford** [comment]
Should be able to specify a subject ID for HBN. Use this case in tests.

**Comment by richford** [comment]
Make the `data` module object oriented. At a minimum we need a `Study` class and a `Subject` class.

- `Study` should accept a `subject_id` init param so that it only downloads the requested subjects.
- If `subject_id = None` just grab the first one.
- On init, `Study` should only populate the list of s3 keys
- Download all subjects in a separate method
- On init, `Subject` should receive a list of s3 keys and populate it's s3 key parameters
- It should have a separate download method
- `Subject.download()` should check to see if files are already there and check against a hash.
- `Study` should have a `list_subjects()` method.

## Implementation suggestion
have a base `Study` class and then an HBN-specific `HBN_Study` class that inherits from it. The `Study` class should call the `list_subjects()` method and then the specific `HBN_study()` should reference the participants.tsv file found in each site.

**Comment by richford** [comment]
Closed by #38
